dcos/dcos-docker

README.md

The route command for OSX didn't work for me using 10.11.5 (El Capitan). With the "add" keyword added to the command I got everything working just fine.

Route command for OSX now works

---

Makefile
common.mk

runs dcos integration tests, can customize
test commands with common.mk

Add make test target

---

Makefile

Previously, the make recipies modified in this commit only worked for
newer versions of make. This change allows it to work with older
versions of make as well.

Update targets to work with older versions of Make.

---

Makefile

```
$ make vagrant
vagrant up
Bringing machine 'dcos-docker' up with 'virtualbox' provider...
==> dcos-docker: Checking if box 'mesosphere/dcos-centos-virtualbox' is up to date...
==> dcos-docker: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> dcos-docker: flag to force provisioning. Provisioners marked to run always will still run.
vagrant ssh -c 'cd /vagrant && make'
centos-7 -> FROM centos:7
coreos -> FROM jess/coreos
debian-jessie -> FROM debian:jessie
fedora-23 -> FROM fedora:23
ubuntu-xenial -> FROM ubuntu:xenial
+ Building the centos-7 base image
...
Creating directories under /etc/mesosphere
Creating role file for slave_public
Configuring DC/OS
Setting and starting DC/OS
Created symlink from …
```

Add `vagrant` make target

---

README.md
Vagrantfile

so that all the `make` commands work right away on login.
Note that a simple `usermod --home=/vagrant vagrant` doesn't work
because the `vagrant` user is logged in; `usermod` disallows that.

cd /vagrant on login

---

Makefile

instead of Google DNS
because Google DNS won't work on every network environment, but 10.0.2.3
is VirtualBox's DNS, which is more likely to work.
Without this, my containers don't have outbound network connectivity,
because it seems that my network is blocking Google DNS.
Cc: @karlkfi

Use 10.0.2.3 as resolver

---

Makefile

in `genconf` target so that artifacts from previous runs don't cause errors like:
```
+ Running genconf
Unable to find image 'mesosphere/dcos-genconf:0ce03387884523f026-58fd0833ce81b6244f' locally
Pulling repository docker.io/mesosphere/dcos-genconf
docker: Error: image mesosphere/dcos-genconf not found.
See 'docker run --help'.
make: *** [genconf] Error 125
```
Cc: @karlkfi

rm dcos-genconf.*.tar

---

README.md

It is definitely incorrect to say "until 1.8.3 is released". Possibly the best solution is to say to avoid 1.8.2. However, since there have been multiple releases since 1.8.2, I believe that it is best to just remove this point. AFAIK, there is no testing of each change to this repository to verify that new setups work with every old version of DC/OS, and so I can imagine that there are other old versions of DC/OS which either do not work or will not work at some point in the future.

Remove 1.8.2 workaround

---

Makefile

This changes `make postflight` to work on DC/OS Enterprise.
- [DCOS-15322](https://jira.mesosphere.com/browse/DCOS-15322) DC/OS Docker - Postflight does not complete on DC/OS Enterprise.
I have tested this by creating clusters with DC/OS Enterprise `master` and DC/OS OSS `master`. Both complete and the commands seem to work at the same time as the old command worked on OSS.
I would appreciate a reviewer doing a similar check to confirm.

[DCOS-15322] Change postflight command to work on both DCOS/OSS and DCOS/E

---

Makefile
README.md

This enables and documents experimental support for running DC/OS Docker on without using systemd.
https://jira.mesosphere.com/browse/DCOS-15862 - Add an option to run DC/OS Docker without systemd
This was taken out of https://github.com/dcos/dcos-docker/pull/36
I have spun up a cluster with `make` and seen that this works.
Some integration tests can be run on this cluster and as a sanity check,
the agent configuration file shows the expected data.
```
$ docker exec dcos-docker-pubagent1 cat /var/lib/dcos/mesos-slave-common
MESOS_SYSTEMD_ENABLE_SUPPORT=true
```
I have spun up a cluster with `make clean; make MESOS_SYSTEMD_ENABLE_SUPPORT=false`:
```
$ docker exec dcos-docker-pubagent1 cat /var/lib/dcos/mesos-slave-common
MESOS_SYSTEMD_ENABLE_SUPPORT=false
```
On each of the above, I ran …

Remove Systemd requirement from DC/OS

---

Makefile

This avoids having to set `HOME_MOUNTS` on environments like TeamCity where $HOME isn't set.
Otherwise a confusing error message is given.
See https://jira.mesosphere.com/browse/DCOS_OSS-1193

Don't set HOME variable where $HOME isn't available

---

Makefile

See https://jira.mesosphere.com/browse/DCOS-16002
I have tested this with `master` by running:
```sh
$ make DOCKER_STORAGEDRIVER=aufs
...
$ cat include/systemd/docker.service  | grep daemon
ExecStart=/usr/bin/docker daemon -D -s aufs --disable-legacy-registry=true --exec-opt=native.cgroupdriver=cgroupfs
$ make clean
...
$ cat include/systemd/docker.service  | grep daemon
ExecStart=/usr/bin/docker daemon -D -s aufs --disable-legacy-registry=true --exec-opt=native.cgroupdriver=cgroupfs
$ make DOCKER_STORAGEDRIVER=overlay
...
$ cat include/systemd/docker.service  | grep daemon
ExecStart=/usr/bin/docker daemon -D -s aufs --disable-legacy-registry=true --exec-opt=native.cgroupdriver=cgroupfs
```
Then with the proposed changes:
```sh
$ make clean
...
rm -f -r …
```

Remove service file directory in `make clean`

---

Makefile

with the latest refactor -diag will be unrecognizable by cobra and double
dash must be used instead. Earlier versions of 3dt should work fine with
either -diag or --diag.

set 3dt diag flag to `--diag`

---

Makefile

in DC/OS >= 1.10 3dt binary has been renamed to `dcos-diagnostics`. The
`--diag` remains the same.
We also do not need the endpoints config (3dt with DC/OS <= 1.9).
This is used for collecting the logs from all nodes and the only reason 3dt
complains about endpoint config is because it is a bug. The info message will
not influence the exit code, so we should be good to just ignore it.

use new binary for postflight

---

Makefile

- add `shopt -s nullglob` flag to ignore the config files that were not
found in `cfg_files`
- add extra locations for endpoint config. Different versions of 3dt are
using endpoint config from various locations. Using an array to try all of
them.

refactor dcos-postflight

---

Makefile

The current Makefile was not written with parallel jobs in mind; instead
all rules are expected to be executed sequentially.
Make this explicit in the Makefile.

Force sequential execution of make rules.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dcos/dcos-docker/57)

Fixed instructions for forcing dcos-docker to use `docker 1.13.1`.

---

Makefile

Setting these hosts is necessary for running the integration tests for Enterprise DC/OS
See https://jira.mesosphere.com/browse/DCOS-17636
To recreate the issue described on JIRA on `master`, I ran the following command:
```
make \
DOCKER_VERSION=1.13.1 \
MESOS_SYSTEMD_ENABLE_SUPPORT=false \
DCOS_GENERATE_CONFIG_PATH=/tmp/dcos_generate_config.ee.sh \
DCOS_PYTEST_CMD='export DCOS_LOGIN_UNAME=admin && \
export DCOS_LOGIN_PW=admin && \
pytest' \
test
```
The issue is not present with this branch.

make test: expose master nodes via environment

---

ci/test-e2e.sh
ci/test-integration.sh
make-defaults.mk

pytest project recommends pytest entry point over py.test. (pytest-dev/pytest#1629, pytest-dev/pytest#1633)

Rename py.test to pytest.

---

Makefile

This makes dcos-docker work with latest DC/OS EE.

Disable fault_domains support.

---

Makefile

Reverts dcos/dcos-docker#66
fault_domain_enabled cannot be used in OSS DC/OS, the set of integration tests relies on
dcos-docker. We should implement a proper mechanism to distinguish OSS vs EE config.yaml for dcos-docker
https://mesosphere.slack.com/archives/C1JEED22F/p1513383301000081

Revert "Disable fault_domains support."

---

include.src/sbin/dcos-postflight

Up until https://github.com/dcos/dcos/pull/2154 Agent AR was serving the root location (i.e. `/`), even though it is incorrect - it should be returning 404.
Now that it has been fixed, a new endpoint needs to be used for AR pooling which is suitable for both Open and EE, Agent and Master. Such an endpoint seems to be `/dcos-metadata/dcos-version.json`.
* https://jira.mesosphere.com/browse/DCOS-19534 `Agent Admin Router: do not serve root location (respond 404)`
Open DC/OS PR: https://github.com/dcos/dcos/pull/2154
EE DC/OS PR: https://github.com/mesosphere/dcos-enterprise/pull/1806
**We will most probably need to adjust integration tests for `1.10` and `master` as well, but I do not know how it can be done.**

Make Admin Router postflight avoid using HTTP call for /

---

Vagrantfile

Time in VirtualBox guest VM's can fall out of sync when the host machine is
suspended and resumed.  You can see this by suspending a host for a few
minutes, wake it up, and compare host and guest clocks.
It seems VirtualBox will not take action until 20min of drift is seen.  This
change will reduce the threshold to 10s.  Details here: http://stackoverflow.com/questions/19490652/how-to-sync-time-on-host-wake-up-within-virtualbox#19492466
The default value can't be seen but after setting, you can do this to see it:
$ VBoxManage guestproperty get dcos-docker "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold"
Value: 10000

improve guest time sync with host

---

Makefile
configure
make-defaults.mk

Options:
- Set `LICENSE_KEY` (file contents)  in `make-config.mk`
- Use `./configure --auto` to read from `./license.txt`
- Use `./configure` and supply a different license path when prompted

Add support for new DC/OS Enterprise 1.11 license key config

---

genconf.src/ip-detect

https://jira.mesosphere.com/browse/DCOS_OSS-2125 - DC/OS Docker - ip_detect script does not work on CoreOS
With this change, a CoreOS cluster starts up on both DC/OS OSS master and DC/OS Enterprise master.
A CentOS cluster still starts up on both DC/OS OSS master and DC/OS Enterprise master.

Enable CoreOS to work by selecting the right `ip` script

---

Makefile

Because it was previously using $(MASTERS), if you had three
master nodes and one agent (public or private), it would attempt
to perform a postflight check for three agents, which would fail.
This change uses $(AGENTS) and $(PUBLIC_AGENTS) for the private
and public agent iterations, respectively.

Use the right variable for seq iteration.
